CREATE TABLE public.verbas_indenizatorias (
	id serial NOT NULL,
	vereador varchar(150) NOT NULL,
	aluguel float8 NOT NULL,
	condominio float8 NOT NULL,
	energia float8 NOT NULL,
	agua float8 NOT NULL,
	iptu_tpei float8 NOT NULL,
	internet_telefone float8 NOT NULL,
	trasporte_hospedagens float8 NOT NULL,
	locacao_automovel float8 NOT NULL,
	pecas_veiculos float8 NOT NULL,
	servicos float8 NOT NULL,
	material_expediente float8 NOT NULL,
	locacao_equipamentos float8 NOT NULL,
	assinaturas_jornais float8 NOT NULL,
	servicos_graficos float8 NOT NULL,
	total_apresentado float8 NOT NULL,
	glosa float8 NOT NULL,
	pago_no_mes float8 NOT NULL,
	media_mensal float8 NOT NULL,
	media_mensal_acumulada float8 NOT NULL,
	"data" varchar(255) NULL,
	"timestamp" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_vereador int4 NULL,
	CONSTRAINT verbas_indenizatorias_pkey PRIMARY KEY (id),
	CONSTRAINT fk FOREIGN KEY (id_vereador) REFERENCES vereadores(id)
);
